//
// AccountIban.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Numer konta w formacie IBAN */
public struct AccountIban: Codable {


}
