//
// AccountForeign.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Numer konta, format dla przelewów zagranicznych */
public struct AccountForeign: Codable {


}
