//
// AccountsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o rachunki / Accounts Request Class */
public struct AccountsRequest: Codable {


    public var requestHeader: RequestHeaderCallback

    /** Znacznik informujący czy request jest przesłany bezpośrednio przez PSU / Is request sent by PSU directly */
    public var isDirectPsu: Bool?

    /** Używane w celu stronicowania danych: numer rachunku rozpoczynający stronę / Account number beginning the page (paging info) */
    public var pageId: String?

    /** Używane w celu stronicowania danych: wielkość strony danych / Page size (paging info) */
    public var perPage: BigDecimal?
    public init(requestHeader: RequestHeaderCallback, isDirectPsu: Bool?, pageId: String?, perPage: BigDecimal?) { 
        self.requestHeader = requestHeader
        self.isDirectPsu = isDirectPsu
        self.pageId = pageId
        self.perPage = perPage
    }

}
