//
// AccountBaseInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa informacji o koncie / Account Information Class */
public struct AccountBaseInfo: Codable {


    /** Numer rachunku (częściowo zamaskowany) / Account number (partly masked) */
    public var accountNumber: String

    /** Nazwa typu rachunku / Account type name */
    public var accountTypeName: String

    /** Typ rachunku / Account type */
    public var accountType: String
    public init(accountNumber: String, accountTypeName: String, accountType: String) { 
        self.accountNumber = accountNumber
        self.accountTypeName = accountTypeName
        self.accountType = accountType
    }

}
