//
// AccountResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi na zapytania o konto PSU / PSU&#x27;s Account Response Class */
public struct AccountResponse: Codable {


    public var responseHeader: ResponseHeader

    public var account: AccountInfo?
    public init(responseHeader: ResponseHeader, account: AccountInfo?) { 
        self.responseHeader = responseHeader
        self.account = account
    }

}
