//
// AccountInfoRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o pojedynczy rachunek / Account Information Request Class */
public struct AccountInfoRequest: Codable {


    public var requestHeader: RequestHeaderAIS

    /** Numer rachunku / Account number */
    public var accountNumber: String
    public init(requestHeader: RequestHeaderAIS, accountNumber: String) { 
        self.requestHeader = requestHeader
        self.accountNumber = accountNumber
    }

}
