//
// AccountInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa informacji o koncie / Account Information Class */
public struct AccountInfo: Codable {


    /** Numer rachunku / Account number */
    public var accountNumber: String

    public var nameAddress: NameAddress

    public var accountType: DictionaryItem?

    /** Nazwa typu rachunku (definiowana przez ASPSP) / Account&#x27;s type name (defined by ASPSP) */
    public var accountTypeName: String?

    /** Nazwa konta ustawiona przez klienta / Account name set by the client */
    public var accountNameClient: String?

    /** Waluta rachunku / Currency */
    public var currency: String?

    /** Dostępne środki - po wykonaniu transakcji / Available funds */
    public var availableBalance: String

    /** Saldo księgowe rachunku - po wykonaniu transakcji / Book balance of the account */
    public var bookingBalance: String

    public var bank: BankAccountInfo?

    public var auxData: Map?
    public init(accountNumber: String, nameAddress: NameAddress, accountType: DictionaryItem?, accountTypeName: String?, accountNameClient: String?, currency: String?, availableBalance: String, bookingBalance: String, bank: BankAccountInfo?, auxData: Map?) { 
        self.accountNumber = accountNumber
        self.nameAddress = nameAddress
        self.accountType = accountType
        self.accountTypeName = accountTypeName
        self.accountNameClient = accountNameClient
        self.currency = currency
        self.availableBalance = availableBalance
        self.bookingBalance = bookingBalance
        self.bank = bank
        self.auxData = auxData
    }

}
