//
// AccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi na zapytania o wiele kont PSU / PSU&#x27;s Multiple Accounts Response Class */
public struct AccountsResponse: Codable {


    public var responseHeader: ResponseHeader

    public var accounts: [AccountBaseInfo]?

    public var pageInfo: PageInfo?
    public init(responseHeader: ResponseHeader, accounts: [AccountBaseInfo]?, pageInfo: PageInfo?) { 
        self.responseHeader = responseHeader
        self.accounts = accounts
        self.pageInfo = pageInfo
    }

}
