//
// AddPaymentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi zlecenia płatności / Payment Add Response Class */
public struct AddPaymentResponse: Codable {


    public var responseHeader: ResponseHeader

    /** Identyfiaktor płatności / Transaction ID */
    public var transactionId: String

    public var generalStatus: PaymentStatus

    /** Status płatności / Detailed payment status */
    public var detailedStatus: String
    public init(responseHeader: ResponseHeader, transactionId: String, generalStatus: PaymentStatus, detailedStatus: String) { 
        self.responseHeader = responseHeader
        self.transactionId = transactionId
        self.generalStatus = generalStatus
        self.detailedStatus = detailedStatus
    }

}
