//
// AuthorizeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o uzyskanie kodu autoryzacyjnego zgodnego z OAuth2 */
public struct AuthorizeRequest: Codable {


    public var requestHeader: RequestHeaderWithoutToken?

    /** Typ odpowiedzi. Wartość stała: code */
    public var responseType: String?

    /** Identyfikator TPP */
    public var clientId: String?

    /** Adres usługi TPP, na które zostanie wykonane przekierowanie po uwierzytelnieniu klienta ASPSP */
    public var redirectUri: String?

    /** Typy zgód o które prosi TPP. Lista identyfikatorów zgodna ze specyfikacją standardu Polish API. */
    public var scope: String?

    public var scopeDetails: ScopeDetailsInput?

    /** Losowa, unikalna w ramach TPP wartość – zabezpieczenie przed atakiem Cross-Site Request Forgery */
    public var state: String?
    public init(requestHeader: RequestHeaderWithoutToken?, responseType: String?, clientId: String?, redirectUri: String?, scope: String?, scopeDetails: ScopeDetailsInput?, state: String?) { 
        self.requestHeader = requestHeader
        self.responseType = responseType
        self.clientId = clientId
        self.redirectUri = redirectUri
        self.scope = scope
        self.scopeDetails = scopeDetails
        self.state = state
    }
    public enum CodingKeys: String, CodingKey { 
        case requestHeader
        case responseType = "response_type"
        case clientId = "client_id"
        case redirectUri = "redirect_uri"
        case scope
        case scopeDetails = "scope_details"
        case state
    }

}
