//
// Bank.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane banku używana w żądaniach AIS / AIS Bank Data Class */
public struct Bank: Codable {


    /** Numer BIC/SWIFT Banku / BIC/SWIFT number */
    public var bicOrSwift: String?

    /** Nazwa Banku / Bank&#x27;s name */
    public var name: String?

    /** Kod Banku, dla przelewów zagranicznych / Bank&#x27;s code */
    public var code: String?

    /** Kod kraju 3166-1 / Country code */
    public var countryCode: String?

    public var address: Address?
    public init(bicOrSwift: String?, name: String?, code: String?, countryCode: String?, address: Address?) { 
        self.bicOrSwift = bicOrSwift
        self.name = name
        self.code = code
        self.countryCode = countryCode
        self.address = address
    }

}
