//
// CurrencyRate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca kursy przewalutowań / Currency rate */
public struct CurrencyRate: Codable {


    /** Kursy przewalutowania / Currency exchange rate */
    public var rate: Double?

    /** Waluta rachunku, kod ISO / from Currency, ISO code */
    public var fromCurrency: String?

    /** Waluta rachunku, kod ISO / to Currency, ISO code */
    public var toCurrency: String?
    public init(rate: Double?, fromCurrency: String?, toCurrency: String?) { 
        self.rate = rate
        self.fromCurrency = fromCurrency
        self.toCurrency = toCurrency
    }

}
