//
// DeleteConsentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o usunięcie zgody na dostęp do AIS */
public struct DeleteConsentRequest: Codable {


    /** Identyfikator zgody / Consent ID */
    public var consentId: String
    public init(consentId: String) { 
        self.consentId = consentId
    }

}
