//
// EatCodeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o uzyskanie kodu autoryzacyjnego zgodnego z OAuth2 na podstawie przekazanego kodu jednorazowego, wygenerowanego w EAT */
public struct EatCodeRequest: Codable {


    public var requestHeader: RequestHeaderWithoutTokenCallback?

    /** Typ odpowiedzi. Wartość stała: code */
    public var responseType: String?

    /** Jednorazowy kod autoryzacyjny wygenerowany przez EAT */
    public var eatCode: String?

    public var eatType: DictionaryItem?

    /** Identyfikator TPP */
    public var clientId: String?

    /** Typy zgód o które prosi TPP. Lista identyfikatorów zgodna ze specyfikacją standardu Polish API. */
    public var scope: String?

    public var scopeDetails: ScopeDetailsInput?

    /** Losowa, unikalna w ramach TPP wartość – zabezpieczenie przed atakiem Cross-Site Request Forgery */
    public var state: String?
    public init(requestHeader: RequestHeaderWithoutTokenCallback?, responseType: String?, eatCode: String?, eatType: DictionaryItem?, clientId: String?, scope: String?, scopeDetails: ScopeDetailsInput?, state: String?) { 
        self.requestHeader = requestHeader
        self.responseType = responseType
        self.eatCode = eatCode
        self.eatType = eatType
        self.clientId = clientId
        self.scope = scope
        self.scopeDetails = scopeDetails
        self.state = state
    }
    public enum CodingKeys: String, CodingKey { 
        case requestHeader
        case responseType = "response_type"
        case eatCode
        case eatType
        case clientId = "client_id"
        case scope
        case scopeDetails = "scope_details"
        case state
    }

}
