//
// GetPaymentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi na pytanie o płatność / Payment Get Response Class */
public struct GetPaymentResponse: Codable {


    /** Identyfiaktor płatności / Transaction ID */
    public var transactionId: String

    public var generalStatus: PaymentStatus

    /** Szczegółowy status płatności / Detailed payment status */
    public var detailedStatus: String
    public init(transactionId: String, generalStatus: PaymentStatus, detailedStatus: String) { 
        self.transactionId = transactionId
        self.generalStatus = generalStatus
        self.detailedStatus = detailedStatus
    }

}
