//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca informacje o zwracanym błędzie / Error class */
public struct ModelError: Codable {


    public var responseHeader: ResponseHeader?

    /** Kod błędu / Error code */
    public var code: String?

    /** Opis błędu / Error message */
    public var message: String?
    public init(responseHeader: ResponseHeader?, code: String?, message: String?) { 
        self.responseHeader = responseHeader
        self.code = code
        self.message = message
    }

}
