//
// PageInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane pozwalajace na korzystanie z mechanizmu stronicowania / Paging Information Class */
public struct PageInfo: Codable {


    /** Użyte w celu stronicowania danych: poprzednia strona (np: numer konta lub transakcji rozpoczynający poprzednią stronę) / Previous page */
    public var previousPage: String?

    /** Użyte w celu stronicowania danych: następna strona (np: numer konta lub transakcji rozpoczynający następną stronę) / Next page */
    public var nextPage: String?
    public init(previousPage: String?, nextPage: String?) { 
        self.previousPage = previousPage
        self.nextPage = nextPage
    }

}
