//
// PaymentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o status płatności / Payment Request Class */
public struct PaymentRequest: Codable {


    public var requestHeader: RequestHeader

    /** Identyfikator płatności / Transaction ID */
    public var transactionId: String
    public init(requestHeader: RequestHeader, transactionId: String) { 
        self.requestHeader = requestHeader
        self.transactionId = transactionId
    }

}
