//
// PaymentDomesticRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zlecenia przelewu krajowego / Domestic Transfer Request Class */
public struct PaymentDomesticRequest: Codable {

    public enum DeliveryMode: String, Codable { 
        case expressD0 = "ExpressD0"
        case standardD1 = "StandardD1"
    }    public enum System: String, Codable { 
        case elixir = "Elixir"
        case expressElixir = "ExpressElixir"
        case sorbnet = "Sorbnet"
        case blueCash = "BlueCash"
        case _internal = "Internal"
    }
    public var requestHeader: RequestHeaderCallback

    public var recipient: RecipientPIS

    public var sender: SenderPIS

    public var transferData: TransferData

    /** ID transakcji nadany przez TPP / Transaction ID (TPP) */
    public var tppTransactionId: String
    /** Tryb pilności / Urgency mode */
    public var deliveryMode: DeliveryMode
    /** Droga jaką przelew ma być rozliczony / The way the transfer should be settled */
    public var system: System?

    /** Czy założyć blokadę (w przypadku np. zlecenia przelewu w dniu wolnym) / Indicates if payment should be holded */
    public var hold: Bool?
    public init(requestHeader: RequestHeaderCallback, recipient: RecipientPIS, sender: SenderPIS, transferData: TransferData, tppTransactionId: String, deliveryMode: DeliveryMode, system: System?, hold: Bool?) { 
        self.requestHeader = requestHeader
        self.recipient = recipient
        self.sender = sender
        self.transferData = transferData
        self.tppTransactionId = tppTransactionId
        self.deliveryMode = deliveryMode
        self.system = system
        self.hold = hold
    }

}
