//
// PaymentsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o statusy wielu płatności / Payments Request Class */
public struct PaymentsRequest: Codable {


    public var requestHeader: RequestHeaderWithoutToken

    public var paymentsId: [String]
    public init(requestHeader: RequestHeaderWithoutToken, paymentsId: [String]) { 
        self.requestHeader = requestHeader
        self.paymentsId = paymentsId
    }

}
