//
// PaymentNonEEARequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zlecenia przelewu zagranicznego innego niż SEPA / NonEEA Transfer Request Class */
public struct PaymentNonEEARequest: Codable {

    public enum DeliveryMode: String, Codable { 
        case expressD0 = "ExpressD0"
        case urgentD1 = "UrgentD1"
        case standardD2 = "StandardD2"
    }    public enum System: String, Codable { 
        case swift = "Swift"
    }
    public var requestHeader: RequestHeaderCallback

    public var recipient: RecipientPISForeign

    public var recipientBank: Bank

    public var sender: SenderPIS

    public var transferData: TransferDataCurrencyRequired

    /** Klauzula kosztowa / The cost clause */
    public var transferCharges: String?

    /** ID transakcji nadany przez TPP / Transaction ID (TPP) */
    public var tppTransactionId: String
    /** Tryb pilności / Urgency mode */
    public var deliveryMode: DeliveryMode
    /** Droga jaką przelew ma być rozliczony / The way the transfer should be settled */
    public var system: System?

    /** Czy założyć blokadę (w przypadku np. zlecenia przelewu w dniu wolnym) / Indicates if payment should be holded */
    public var hold: Bool?
    public init(requestHeader: RequestHeaderCallback, recipient: RecipientPISForeign, recipientBank: Bank, sender: SenderPIS, transferData: TransferDataCurrencyRequired, transferCharges: String?, tppTransactionId: String, deliveryMode: DeliveryMode, system: System?, hold: Bool?) { 
        self.requestHeader = requestHeader
        self.recipient = recipient
        self.recipientBank = recipientBank
        self.sender = sender
        self.transferData = transferData
        self.transferCharges = transferCharges
        self.tppTransactionId = tppTransactionId
        self.deliveryMode = deliveryMode
        self.system = system
        self.hold = hold
    }

}
