//
// PaymentsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi na pytanie o wiele płatności */
public struct PaymentsResponse: Codable {


    public var responseHeader: ResponseHeader

    public var payments: [PaymentInfo]?
    public init(responseHeader: ResponseHeader, payments: [PaymentInfo]?) { 
        self.responseHeader = responseHeader
        self.payments = payments
    }

}
