//
// PrivilegeAisAspspIn.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Lista atrybutów uprawnienia usługi AIS będących przedmiotem zapytania o zgodę PSU / The list of attributes of the privilege of the AIS service that are the subject of the request for PSU&#x27;s consent */
public struct PrivilegeAisAspspIn: Codable {


    /** Limit of usages */
    public var scopeUsageLimit: Int?

    /** How much history is allowed in days */
    public var maxAllowedHistoryLong: Int
    public init(scopeUsageLimit: Int?, maxAllowedHistoryLong: Int) { 
        self.scopeUsageLimit = scopeUsageLimit
        self.maxAllowedHistoryLong = maxAllowedHistoryLong
    }

}
