//
// PrivilegePayment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Lista atrybutów uprawnienia do żądania statusu płatności / The list of attributes of the payment status request privilege */
public struct PrivilegePayment: Codable {


    /** Limit of usages */
    public var scopeUsageLimit: Int?

    /** Identyfikator płatności / Transaction ID */
    public var transactionId: String?
    public init(scopeUsageLimit: Int?, transactionId: String?) { 
        self.scopeUsageLimit = scopeUsageLimit
        self.transactionId = transactionId
    }

}
