//
// PrivilegeAisAspspOutSimple.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Lista atrybutów uprawnienia usługi AIS dla których została wyrażona zgoda przez PSU / The list of attributes of the privilege of the AIS service that the PSU&#x27;s consent has been confirmed */
public struct PrivilegeAisAspspOutSimple: Codable {


    /** Limit of usages */
    public var scopeUsageLimit: Int?
    public init(scopeUsageLimit: Int?) { 
        self.scopeUsageLimit = scopeUsageLimit
    }

}
