//
// PrivilegeCaF.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Uprawnienie usługi CAF, będącej przedmiotem zapytania o zgodę PSU / The privilege of the AIS service that is the subject of the request for PSU&#x27;s consent */
public struct PrivilegeCaF: Codable {


    /** Limit of usages */
    public var scopeUsageLimit: Int?

    public var amount: BigDecimal

    public var currency: String
    public init(scopeUsageLimit: Int?, amount: BigDecimal, currency: String) { 
        self.scopeUsageLimit = scopeUsageLimit
        self.amount = amount
        self.currency = currency
    }

}
