//
// PrivilegeAisAspspOut.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Lista atrybutów uprawnienia usługi AIS dla których została wyrażona zgoda przez PSU / The list of attributes of the privilege of the AIS service that the PSU&#x27;s consent has been confirmed */
public struct PrivilegeAisAspspOut: Codable {


    /** Limit of usages */
    public var scopeUsageLimit: Int?

    /** How much history is allowed in days */
    public var maxAllowedHistoryLong: Int

    /** Minimum date for transaction that will be returned */
    public var notBefore: String

    /** Maximum date for transaction that will be returned */
    public var notAfter: String
    public init(scopeUsageLimit: Int?, maxAllowedHistoryLong: Int, notBefore: String, notAfter: String) { 
        self.scopeUsageLimit = scopeUsageLimit
        self.maxAllowedHistoryLong = maxAllowedHistoryLong
        self.notBefore = notBefore
        self.notAfter = notAfter
    }

}
