//
// PrivilegeTaxTransfer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Lista atrybutów uprawnienia do inicjacji przelewu urzędu podatkowego / The list of attributes of the tax transfer request initiation privilege */
public struct PrivilegeTaxTransfer: Codable {


    /** Limit of usages */
    public var scopeUsageLimit: Int?

    public var recipient: RecipientPISTax?

    public var sender: SenderPIS?

    public var transferData: TransferDataCurrencyRequired?

    public var usInfo: TransactionInfoTax?
    public init(scopeUsageLimit: Int?, recipient: RecipientPISTax?, sender: SenderPIS?, transferData: TransferDataCurrencyRequired?, usInfo: TransactionInfoTax?) { 
        self.scopeUsageLimit = scopeUsageLimit
        self.recipient = recipient
        self.sender = sender
        self.transferData = transferData
        self.usInfo = usInfo
    }

}
