//
// PrivilegeAisAspspInSimple.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Lista atrybutów uprawnienia usługi AIS będących przedmiotem zapytania o zgodę PSU / The list of attributes of the privilege of the AIS service that are the subject of the request for PSU&#x27;s consent */
public struct PrivilegeAisAspspInSimple: Codable {


    /** Limit of usages */
    public var scopeUsageLimit: Int?
    public init(scopeUsageLimit: Int?) { 
        self.scopeUsageLimit = scopeUsageLimit
    }

}
