//
// RecipientPIS.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane odbiorcy używana w żądaniach PIS / PIS Recipient Data Class */
public struct RecipientPIS: Codable {


    public var accountNumber: AccountIban

    /** Recipient&#x27;s name / Name */
    public var name: String

    public var address: Address?
    public init(accountNumber: AccountIban, name: String, address: Address?) { 
        self.accountNumber = accountNumber
        self.name = name
        self.address = address
    }

}
