//
// RecipientPISForeign.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane odbiorcy używana w żądaniach PIS dla operacji zagranicznych / PIS foreign Recipient Data Class */
public struct RecipientPISForeign: Codable {


    public var accountNumber: AccountForeign

    /** Recipient&#x27;s name / Name */
    public var name: String

    public var address: Address?
    public init(accountNumber: AccountForeign, name: String, address: Address?) { 
        self.accountNumber = accountNumber
        self.name = name
        self.address = address
    }

}
