//
// RecipientPISTax.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane odbiorcy używana w żądaniach PIS dla operacji podatkowych / PIS Tax Recipient Data Class */
public struct RecipientPISTax: Codable {


    public var accountNumber: AccountIban

    public var address: Address
    public init(accountNumber: AccountIban, address: Address) { 
        self.accountNumber = accountNumber
        self.address = address
    }

}
