//
// ResponseHeader.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca zwrotne metadane / Metadata Class */
public struct ResponseHeader: Codable {


    /** Identyfikator żądania / Request ID */
    public var requestId: String?

    /** Data odpowiedzi, format: 2017-11-24T14:13:05.424Z / Send date */
    public var sendDate: String?

    /** Znacznik określający czy odpowiedz zostanie przekazana w formie wywołania zwrotnego. true - gdy odpowiedz w formie wywołania zwrotnego. Inna dopuszczalna wartość to false. */
    public var isCallback: Bool?
    public init(requestId: String?, sendDate: String?, isCallback: Bool?) { 
        self.requestId = requestId
        self.sendDate = sendDate
        self.isCallback = isCallback
    }

}
