//
// ScopeDetailsInputPrivilegeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Pełna lista uprawnień będących przedmiotem zapytania o zgodę PSU / The list of all privileges that are the subject of the request for PSU&#x27;s consent */
public struct ScopeDetailsInputPrivilegeList: Codable {


    public var aisaccounts: PrivilegeAisAspspInSimple?

    public var aisaccount: PrivilegeAisAspspInSimple?

    public var aisholds: PrivilegeAisAspspIn?

    public var aistransactionsDone: PrivilegeAisAspspIn?

    public var aistransactionsPending: PrivilegeAisAspspIn?

    public var aistransactionsRejected: PrivilegeAisAspspIn?

    public var aistransactionDetail: PrivilegeAisAspspInSimple?

    public var pispayment: PrivilegePayment?

    public var pisdomestic: PrivilegeDomesticTransfer?

    public var pisEEA: PrivilegeForeignTransferEEA?

    public var pisnonEEA: PrivilegeForeignTransferNonEEA?

    public var pistax: PrivilegeTaxTransfer?

    public var cafconfirmationOfFunds: PrivilegeCaF?
    public init(aisaccounts: PrivilegeAisAspspInSimple?, aisaccount: PrivilegeAisAspspInSimple?, aisholds: PrivilegeAisAspspIn?, aistransactionsDone: PrivilegeAisAspspIn?, aistransactionsPending: PrivilegeAisAspspIn?, aistransactionsRejected: PrivilegeAisAspspIn?, aistransactionDetail: PrivilegeAisAspspInSimple?, pispayment: PrivilegePayment?, pisdomestic: PrivilegeDomesticTransfer?, pisEEA: PrivilegeForeignTransferEEA?, pisnonEEA: PrivilegeForeignTransferNonEEA?, pistax: PrivilegeTaxTransfer?, cafconfirmationOfFunds: PrivilegeCaF?) { 
        self.aisaccounts = aisaccounts
        self.aisaccount = aisaccount
        self.aisholds = aisholds
        self.aistransactionsDone = aistransactionsDone
        self.aistransactionsPending = aistransactionsPending
        self.aistransactionsRejected = aistransactionsRejected
        self.aistransactionDetail = aistransactionDetail
        self.pispayment = pispayment
        self.pisdomestic = pisdomestic
        self.pisEEA = pisEEA
        self.pisnonEEA = pisnonEEA
        self.pistax = pistax
        self.cafconfirmationOfFunds = cafconfirmationOfFunds
    }
    public enum CodingKeys: String, CodingKey { 
        case aisaccounts = "ais:accounts"
        case aisaccount = "ais:account"
        case aisholds = "ais:holds"
        case aistransactionsDone = "ais:transactionsDone"
        case aistransactionsPending = "ais:transactionsPending"
        case aistransactionsRejected = "ais:transactionsRejected"
        case aistransactionDetail = "ais:transactionDetail"
        case pispayment = "pis:payment"
        case pisdomestic = "pis:domestic"
        case pisEEA = "pis:EEA"
        case pisnonEEA = "pis:nonEEA"
        case pistax = "pis:tax"
        case cafconfirmationOfFunds = "caf:confirmationOfFunds"
    }

}
