//
// SenderRecipient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane nadawcy/odbiorcy używana w żądaniach AIS / AIS Sender Recipient Data Class */
public struct SenderRecipient: Codable {


    /** Numer konta odbiorcy / Account number */
    public var accountNumber: String?

    /** Numer wirtualny rachunku odbiorcy w formacie IBAN / Virtual account name */
    public var accountMassPayment: String?

    public var bank: Bank?

    public var nameAddress: NameAddress?
    public init(accountNumber: String?, accountMassPayment: String?, bank: Bank?, nameAddress: NameAddress?) { 
        self.accountNumber = accountNumber
        self.accountMassPayment = accountMassPayment
        self.bank = bank
        self.nameAddress = nameAddress
    }

}
