//
// SenderPIS.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane nadawcy używana w żądaniach PIS / PIS Sender Data Class */
public struct SenderPIS: Codable {


    public var accountNumber: AccountIban?

    /** Nazwa nadawcy / Sender name */
    public var name: String?
    public init(accountNumber: AccountIban?, name: String?) { 
        self.accountNumber = accountNumber
        self.name = name
    }

}
