//
// SocialSecurityPayor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa informacji o płatniku do ZUS / Polish Social Security Institution (ZUS) Payor Information Class */
public struct SocialSecurityPayor: Codable {

    public enum AdditionalPayorIdType: String, Codable { 
        case p = "P"
        case r = "R"
        case _1 = "1"
        case _2 = "2"
    }
    /** Numer Identyfikacji Podatkowej / Payor&#x27;s Tax Identification Number */
    public var nip: String?

    /** Dodatkowy numer identyfikacyjny płatnika / Payor&#x27;s additional identification number */
    public var additionalPayorId: String?
    /** Typ dodatkowego identyfikatora płatnika / Payor&#x27;s additional identifier type */
    public var additionalPayorIdType: AdditionalPayorIdType?
    public init(nip: String?, additionalPayorId: String?, additionalPayorIdType: AdditionalPayorIdType?) { 
        self.nip = nip
        self.additionalPayorId = additionalPayorId
        self.additionalPayorIdType = additionalPayorIdType
    }

}
