//
// TransferDataCurrencyRequired.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zawierająca dane przelewu / Transfer Data Class */
public struct TransferDataCurrencyRequired: Codable {


    /** Pole opisujące przelew / Description */
    public var _description: String?

    /** Kwota przelewu / Amount */
    public var amount: String?

    /** Data wykonania przelewu / Date when the transfer was executed (YYYY-MM-DD) */
    public var executionDate: Date?
    public init(_description: String?, amount: String?, executionDate: Date?) { 
        self._description = _description
        self.amount = amount
        self.executionDate = executionDate
    }
    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case amount
        case executionDate
    }

}
