//
// TransactionInfoZUS.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa informacji danych dla przelewu do ZUS / ZUS Transfer Information Class */
public struct TransactionInfoZUS: Codable {


    public var payerInfo: SocialSecurityPayor?

    /** Typ wpłaty / Contribution type */
    public var contributionType: String?

    /** Numer deklaracji / Contribution identifier */
    public var contributionId: String?

    /** Okres deklaracji / Contribution period, Format: MMYYYY */
    public var contributionPeriod: String?

    /** Identyfikator typu płatności / Payment type ID */
    public var paymentTypeId: String?

    /** Numer tytułu wykonawczego / Obligation identifier or number */
    public var obligationId: String?
    public init(payerInfo: SocialSecurityPayor?, contributionType: String?, contributionId: String?, contributionPeriod: String?, paymentTypeId: String?, obligationId: String?) { 
        self.payerInfo = payerInfo
        self.contributionType = contributionType
        self.contributionId = contributionId
        self.contributionPeriod = contributionPeriod
        self.paymentTypeId = paymentTypeId
        self.obligationId = obligationId
    }

}
