//
// TransactionPendingInfoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi zawierająca listę transakcji pending / Pending Transaction Information Response Class */
public struct TransactionPendingInfoResponse: Codable {


    public var responseHeader: ResponseHeader

    public var transactions: [TransactionPendingInfo]?

    public var pageInfo: PageInfo?
    public init(responseHeader: ResponseHeader, transactions: [TransactionPendingInfo]?, pageInfo: PageInfo?) { 
        self.responseHeader = responseHeader
        self.transactions = transactions
        self.pageInfo = pageInfo
    }

}
