//
// TransactionDetailResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi na zapytanie o transakcję /  Transaction Detail Response Class */
public struct TransactionDetailResponse: Codable {


    public var responseHeader: ResponseHeader

    public var baseInfo: TransactionInfo

    public var zusInfo: TransactionInfoZUS?

    public var usInfo: TransactionInfoTax?

    public var cardInfo: TransactionInfoCard?

    /** Data kursu waluty, YYYY-MM-DDThh:mm:ss[.mmm] / Date of the currency exchange rate */
    public var currencyDate: Date?

    public var transactionRate: [CurrencyRate]?

    /** Waluta oryginalna transakcji, kod ISO / Currency of the transaction, ISO code */
    public var baseCurrency: String?

    /** Kwota w oryginalnej walucie / Amount of the transaction */
    public var amountBaseCurrency: String?

    /** Unikalny identyfikator instrumentu płatniczego, za którego pomocą wykonano transakcję / Payment Instrument ID */
    public var usedPaymentInstrumentId: String?

    /** Unikalny identyfikator transakcji po stronie TPP / Transaction ID (TPP) */
    public var tppTransactionId: String?

    /** Nazwa TPP / TPP name */
    public var tppName: String?

    /** Przyczyna odrzucenia / Reason for rejection */
    public var rejectionReason: String?

    /** Data ważności blokady */
    public var holdExpirationDate: String?
    public init(responseHeader: ResponseHeader, baseInfo: TransactionInfo, zusInfo: TransactionInfoZUS?, usInfo: TransactionInfoTax?, cardInfo: TransactionInfoCard?, currencyDate: Date?, transactionRate: [CurrencyRate]?, baseCurrency: String?, amountBaseCurrency: String?, usedPaymentInstrumentId: String?, tppTransactionId: String?, tppName: String?, rejectionReason: String?, holdExpirationDate: String?) { 
        self.responseHeader = responseHeader
        self.baseInfo = baseInfo
        self.zusInfo = zusInfo
        self.usInfo = usInfo
        self.cardInfo = cardInfo
        self.currencyDate = currencyDate
        self.transactionRate = transactionRate
        self.baseCurrency = baseCurrency
        self.amountBaseCurrency = amountBaseCurrency
        self.usedPaymentInstrumentId = usedPaymentInstrumentId
        self.tppTransactionId = tppTransactionId
        self.tppName = tppName
        self.rejectionReason = rejectionReason
        self.holdExpirationDate = holdExpirationDate
    }

}
