//
// TransactionHoldRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o transakcje / Transaction Information Request Class */
public struct TransactionHoldRequest: Codable {


    public var requestHeader: RequestHeaderAISCallback?

    /** Numer rachunku / Account number */
    public var accountNumber: String?

    /** Element filtru: transacje od podanego identyfikatora transakcji / Filter element */
    public var transactionIdFrom: String?

    /** Element filtru: data transakcji od, YYYY-MM-DD / Filter element */
    public var transactionDateFrom: Date?

    /** Element filtru: data transakcji do, YYYY-MM-DD / Filter element */
    public var transactionDateTo: Date?

    /** Element filtru: data księgowania od, YYYY-MM-DD / Filter element */
    public var bookingDateFrom: Date?

    /** Element filtru: data księgowania do, YYYY-MM-DD / Filter element */
    public var bookingDateTo: Date?

    /** Element filtru: kwota od / Filter element */
    public var minAmount: String?

    /** Element filtru: kwota do / Filter element */
    public var maxAmount: String?

    /** Używane w celu stronicowania danych: numer transakcji rozpoczynający stronę / Transaction number beginning the page (paging info) */
    public var pageId: String?

    /** Używane w celu stronicowania danych: wielkość strony danych / Page size (paging info) */
    public var perPage: BigDecimal?
    public init(requestHeader: RequestHeaderAISCallback?, accountNumber: String?, transactionIdFrom: String?, transactionDateFrom: Date?, transactionDateTo: Date?, bookingDateFrom: Date?, bookingDateTo: Date?, minAmount: String?, maxAmount: String?, pageId: String?, perPage: BigDecimal?) { 
        self.requestHeader = requestHeader
        self.accountNumber = accountNumber
        self.transactionIdFrom = transactionIdFrom
        self.transactionDateFrom = transactionDateFrom
        self.transactionDateTo = transactionDateTo
        self.bookingDateFrom = bookingDateFrom
        self.bookingDateTo = bookingDateTo
        self.minAmount = minAmount
        self.maxAmount = maxAmount
        self.pageId = pageId
        self.perPage = perPage
    }

}
