//
// TransactionDetailRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa zapytania o pojedynczą transakcję / Transaction Detail Request Class */
public struct TransactionDetailRequest: Codable {


    public var requestHeader: RequestHeaderAIS

    /** ID transakcji / Transaction ID */
    public var transactionId: String

    /** Numer konta nadawcy / Sender account number */
    public var accountNumber: String?

    /** Data zaksięgowania operacji, YYYY-MM-DD / Transaction booking date */
    public var bookingDate: Date?
    public init(requestHeader: RequestHeaderAIS, transactionId: String, accountNumber: String?, bookingDate: Date?) { 
        self.requestHeader = requestHeader
        self.transactionId = transactionId
        self.accountNumber = accountNumber
        self.bookingDate = bookingDate
    }

}
