//
// TransactionRejectedInfoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa odpowiedzi zawierająca listę transakcji rejected / Rejected Transaction Information Response Class */
public struct TransactionRejectedInfoResponse: Codable {


    public var responseHeader: ResponseHeader

    public var transactions: [TransactionRejectedInfo]?

    public var pageInfo: PageInfo?
    public init(responseHeader: ResponseHeader, transactions: [TransactionRejectedInfo]?, pageInfo: PageInfo?) { 
        self.responseHeader = responseHeader
        self.transactions = transactions
        self.pageInfo = pageInfo
    }

}
