//
// TransactionInfoTax.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa informacji danych dla przelewu podatkowego do Urzędu Skarbowego lub Izby Celnej / Tax Transfer */
public struct TransactionInfoTax: Codable {


    public var payerInfo: Payor

    /** Symbol formularza Urzędu Skarbowego lub Izby Celnej / Tax authority form symbol */
    public var formCode: String

    /** Numer okresu / Period number */
    public var periodId: String

    /** Typ okresu / Period type */
    public var periodType: String

    /** Rok okresu / Period year */
    public var year: BigDecimal

    /** Identyfikator zobowiązania, z którego wynika należność podatku np. decyzja, tytuł wykonawczy, postanowienie / Obligation ID */
    public var obligationId: String?

    /** Nazwa urzędu skarbowego lub izby celnej / The name of the Tax Authority */
    public var taxAuthorityName: String?
    public init(payerInfo: Payor, formCode: String, periodId: String, periodType: String, year: BigDecimal, obligationId: String?, taxAuthorityName: String?) { 
        self.payerInfo = payerInfo
        self.formCode = formCode
        self.periodId = periodId
        self.periodType = periodType
        self.year = year
        self.obligationId = obligationId
        self.taxAuthorityName = taxAuthorityName
    }

}
