//
// TransactionInfoCard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Klasa reprezentująca informacje o karcie w ramach transakcji / Transaction Card Information Class */
public struct TransactionInfoCard: Codable {


    /** Właściciel karty / Card holder */
    public var cardHolder: String?

    /** Numer karty / Card number */
    public var cardNumber: String?
    public init(cardHolder: String?, cardNumber: String?) { 
        self.cardHolder = cardHolder
        self.cardNumber = cardNumber
    }

}
